openapi: 3.0.3
info:
  title: DLPZ Shortener API
  description: |
    API REST pour le raccourcissement d'URLs développée avec Symfony.
    
    ## Fonctionnalités
    - Raccourcissement d'URLs avec codes courts de 6 caractères
    - Stockage JSON sans base de données
    - Statistiques de clics
    - Gestion complète des URLs (CRUD)
    - Redirection automatique
    
    ## Format des données
    Toutes les dates sont au format ISO 8601 (UTC) : `2025-01-18T12:00:00Z`
    
    ## Codes de réponse
    - `201` : Création réussie
    - `200` : Succès
    - `400` : Erreur de validation
    - `404` : Ressource non trouvée
    - `500` : Erreur serveur
  version: 1.0.0
  contact:
    name: Dorian Lopez
    url: https://dorianlopez.fr
    email: contact@dorianlopez.fr
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://dlpz.fr
    description: Serveur de production
  - url: http://localhost:8000
    description: Serveur de développement

paths:
  /api/shorten:
    post:
      summary: Raccourcir une URL
      description: Crée un code court unique pour une URL longue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
                  format: uri
                  example: "https://example.com"
      responses:
        '201':
          description: URL raccourcie avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
                    example: "https://dlpz.fr/abc123"
        '400':
          description: URL invalide
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "URL invalide"
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Une erreur interne s'est produite"

  /{code}:
    get:
      summary: Rediriger vers l'URL originale
      description: Redirige automatiquement vers l'URL originale associée au code court
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
          example: "abc123"
      responses:
        '301':
          description: Redirection vers l'URL originale
        '404':
          description: Code court introuvable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Code court introuvable"

  /api/urls:
    get:
      summary: Obtenir toutes les URLs
      description: Retourne la liste de toutes les URLs stockées
      responses:
        '200':
          description: Liste des URLs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                      example: "abc123"
                    original:
                      type: string
                      example: "https://example.com"
                    createdAt:
                      type: string
                      format: date-time
                      example: "2025-01-18T12:00:00Z"
                    clicks:
                      type: integer
                      example: 5
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Une erreur interne s'est produite"

  /api/urls/{code}:
    delete:
      summary: Supprimer une URL
      description: Supprime une URL raccourcie du système
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
          example: "abc123"
      responses:
        '200':
          description: URL supprimée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  deleted:
                    type: boolean
                    example: true
        '404':
          description: Code court introuvable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Code court introuvable"
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Une erreur interne s'est produite"

  /api/urls/{code}/stats:
    get:
      summary: Obtenir les statistiques d'une URL
      description: Récupère les statistiques détaillées d'une URL raccourcie
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
          example: "abc123"
      responses:
        '200':
          description: Statistiques de l'URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: "abc123"
                  original:
                    type: string
                    example: "https://example.com"
                  createdAt:
                    type: string
                    format: date-time
                    example: "2025-01-18T12:00:00Z"
                  clicks:
                    type: integer
                    example: 15
        '404':
          description: Code court introuvable
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Code court introuvable"
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Une erreur interne s'est produite"

  /api/health:
    get:
      summary: Vérifier l'état de l'API
      description: Endpoint de santé pour vérifier que l'API fonctionne
      responses:
        '200':
          description: API en bon état
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-01-18 10:30:00"
                  service:
                    type: string
                    example: "URL Shortener API"